import React from 'react';
import Project from "./Project";

const Portfolio = (props) => {
      const projects = [{
        classEffect: "bounceInLeft",
        delay: "100ms",
        duration: "1s",
        href: "https://seryogagithub.github.io/projects/bestplitka/",
        src: '@/img/portfolio/1.jpg',
        alt: "bestplitka"
      }, {
        classEffect: "bounceInUp",
        delay: "700ms",
        duration: "1.5s",
        href: "https://seryogagithub.github.io/projects/bss/",
        src: '@/img/portfolio/2.jpg',
        alt: "bss"
      }, {
        classEffect: "bounceInRight",
        delay: "500ms",
        duration: "2s",
        href: "https://seryogagithub.github.io/projects/colgate/",
        src: '@/img/portfolio/3.jpg',
        alt: "colgate"
      }, {
        classEffect: "rollIn",
        delay: "1500ms",
        duration: "1s",
        href: "https://seryogagithub.github.io/projects/fifa/",
        src: '@/img/portfolio/4.jpg',
        alt: "fifa"
      }, {
        classEffect: "bounceInDown",
        delay: "500ms",
        duration: "2s",
        href: "https://seryogagithub.github.io/projects/houseStaff/",
        src: '@/img/portfolio/5.jpg',
        alt: "houseStaff"
      }, {
        classEffect: "lightSpeedIn",
        delay: "300ms",
        duration: "1s",
        href: "https://seryogagithub.github.io/projects/kudu/",
        src: '@/img/portfolio/6.jpg',
        alt: "kudu"
      }, {
        classEffect: "bounceInLeft",
        delay: "1000ms",
        duration: "2s",
        href: "https://seryogagithub.github.io/projects/tow/",
        src: '@/img/portfolio/7.jpg',
        alt: "tow"
      }, {
        classEffect: "bounceInDown",
        delay: "200ms",
        duration: "1s",
        href: "https://seryogagithub.github.io/projects/visa/",
        src: '@/img/portfolio/8.jpg',
        alt: "visa"
      }, {
        classEffect: "bounceInRight",
        delay: "1500ms",
        duration: "2s",
        href: "http://www.inform-vs.ru/",
        src: '@/img/portfolio/9.jpg',
        alt: "inform-vs"
      }, {
        classEffect: "rollIn",
        delay: "500ms",
        duration: "1.5s",
        href: "http://ortomed.com.ua/",
        src: '@/img/portfolio/10.jpg',
        alt: "ortomed"
      }, {
        classEffect: "bounceInDown",
        delay: "300ms",
        duration: "3s",
        href: "http://sklad-pro.com/",
        src: '@/img/portfolio/11.jpg',
        alt: "sklad-pro"
      }, {
        classEffect: "bounceInRight",
        delay: "500ms",
        duration: "1s",
        href: "https://meets.com/login",
        src: '@/img/portfolio/13.jpg',
        alt: "meets.com"
      }, {
        classEffect: "bounceInDown",
        delay: "800ms",
        duration: "0.5s",
        href: "https://seryogagithub.github.io/projects/language/",
        src: '@/img/portfolio/14.jpg',
        alt: "arabic-school"
      }, {
        classEffect: "bounceInLeft",
        delay: "500ms",
        duration: "1s",
        href: "http://html.dimbrowsky.info/chernjak/",
        src: '@/img/portfolio/17.jpg',
        alt: "chernjak"
      }, {
        classEffect: "bounceInDown",
        delay: "800ms",
        duration: "0.5s",
        href: "http://html.dimbrowsky.info/auto/",
        src: '@/img/portfolio/20.jpg',
        alt: "auto"
      }, {
        classEffect: "bounceInLeft",
        delay: "500ms",
        duration: "1s",
        href: "http://html.dimbrowsky.info/circus/",
        src: '@/img/portfolio/15.jpg',
        alt: "circus"
      }, {
        classEffect: "bounceInRight",
        delay: "400ms",
        duration: "1s",
        href: "http://html.dimbrowsky.info/chetkin/",
        src: '@/img/portfolio/16.jpg',
        alt: "chetkin"
      }, {
        classEffect: "bounceInDown",
        delay: "200ms",
        duration: "1s",
        href: "http://dimbrowsky.com/km/",
        src: '@/img/portfolio/18.jpg',
        alt: "km"
      }, {
        classEffect: "bounceInRight",
        delay: "1500ms",
        duration: "2s",
        href: "https://carbonconsulting.com.ua/",
        src: '@/img/portfolio/19.jpg',
        alt: "carbonconsulting"
      }, {
        classEffect: "bounceInUp",
        delay: "300ms",
        duration: "1s",
        href: "http://rubineta.com/b2b/",
        src: '@/img/portfolio/21.jpg',
        alt: "rubineta"
      }, {
        classEffect: "rollIn",
        delay: "1500ms",
        duration: "2s",
        href: "http://html.dimbrowsky.info/art/",
        src: '@/img/portfolio/22.jpg',
        alt: "art"
      }, {
        classEffect: "bounceInDown",
        delay: "200ms",
        duration: "1s",
        href: "http://html.dimbrowsky.info/tehno/",
        src: '@/img/portfolio/24.jpg',
        alt: "tehno"
      }, {
        classEffect: "bounceInLeft",
        delay: "900ms",
        duration: "2s",
        href: "http://imperialgarage.net/auto/",
        src: '@/img/portfolio/23.jpg',
        alt: ""
      }, {
        classEffect: "bounceInUp",
        delay: "700ms",
        duration: "1.5s",
        href: "http://html.dimbrowsky.info/tech-razv/",
        src: '@/img/portfolio/25.jpg',
        alt: "tech-razv"
      }, {
        classEffect: "lightSpeedIn",
        delay: "1500ms",
        duration: "0.4s",
        href: "https://seryogagithub.github.io/projects/ubm/",
        src: '@/img/portfolio/26.jpg',
        alt: "ubm"
      }, {
        classEffect: "bounceInLeft",
        delay: "500ms",
        duration: "0.6s",
        href: "https://seryogagithub.github.io/projects/millioneris/",
        src: '@/img/portfolio/27.jpg',
        alt: "millioneris"
      }, {
        classEffect: "bounceInUp",
        delay: "700ms",
        duration: "0.4s",
        href: "https://seryogagithub.github.io/projects/simpleat/",
        src: '@/img/portfolio/28.jpg',
        alt: "simpleat"
      }, {
        classEffect: "bounceInUp",
        delay: "400ms",
        duration: "0.4s",
        href: "https://seryogagithub.github.io/projects/2ru2/",
        src: '@/img/portfolio/29.jpg',
        alt: "2ru2"
      }, {
        classEffect: "bounceInUp",
        delay: "100ms",
        duration: "0.7s",
        href: "http://html.dimbrowsky.info/mg-studia/",
        src: '@/img/portfolio/30.jpg',
        alt: "mg-studia"
      }, {
        classEffect: "bounceInDown",
        delay: "200ms",
        duration: "1s",
        href: "https://seryogagithub.github.io/projects/enginering/",
        src: '@/img/portfolio/31.jpg',
        alt: "enginering"
      }, {
        classEffect: "bounceInUp",
        delay: "700ms",
        duration: "0.5s",
        href: "https://seryogagithub.github.io/projects/aist/",
        src: '@/img/portfolio/32.jpg',
        alt: "aist"
      }, {
        classEffect: "bounceInLeft",
        delay: "500ms",
        duration: "0.4s",
        href: "http://new.zr-code.com/",
        src: '@/img/portfolio/33.jpg',
        alt: "zr"
      }, {
        classEffect: "rollIn",
        delay: "1500ms",
        duration: "1.2s",
        href: "http://new.zr-code.com/project-page.html",
        src: '@/img/portfolio/34.jpg',
        alt: "zr-project"
      }, {
        classEffect: "rollIn",
        delay: "1500ms",
        duration: "2s",
        href: "https://seryogagithub.github.io/projects/zoom/",
        src: '@/img/portfolio/35.jpg',
        alt: "zoom"
      }];

  let projectComponents = projects.map( e => <Project key={e.alt} classEffect={e.classEffect}/>);
  return (
      <main>
        <div className="center">
          <h1 className="text-center title-page">
            Портфоліо
          </h1>
          <div className="pane">
            Дані роботи виконані мною. Вказані роботи можуть бути відображенні частково через схожість сторінок. Нажаль
            більшість робіт втрачено по різним причинам :(
          </div>
          <div className="grid">
            {projectComponents}
          </div>
        </div>
      </main>
  );
}
  ;

  export default Portfolio;