let state = {
  projects: [
    {
      classEffect: "bounceInLeft",
      delay: "100ms",
      duration: "1s",
      href: "https://seryogagithub.github.io/projects/bestplitka/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/1.jpg?raw=true',
      alt: "bestplitka"
    }, {
      classEffect: "bounceInUp",
      delay: "700ms",
      duration: "1.5s",
      href: "https://seryogagithub.github.io/projects/bss/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/2.jpg?raw=true',
      alt: "bss"
    }, {
      classEffect: "bounceInRight",
      delay: "500ms",
      duration: "2s",
      href: "https://seryogagithub.github.io/projects/colgate/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/3.jpg?raw=true',
      alt: "colgate"
    }, {
      classEffect: "rollIn",
      delay: "1500ms",
      duration: "1s",
      href: "https://seryogagithub.github.io/projects/fifa/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/4.jpg?raw=true',
      alt: "fifa"
    }, {
      classEffect: "bounceInDown",
      delay: "500ms",
      duration: "2s",
      href: "https://seryogagithub.github.io/projects/houseStaff/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/5.jpg?raw=true',
      alt: "houseStaff"
    }, {
      classEffect: "lightSpeedIn",
      delay: "300ms",
      duration: "1s",
      href: "https://seryogagithub.github.io/projects/kudu/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/6.jpg?raw=true',
      alt: "kudu"
    }, {
      classEffect: "bounceInLeft",
      delay: "1000ms",
      duration: "2s",
      href: "https://seryogagithub.github.io/projects/tow/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/7.jpg?raw=true',
      alt: "tow"
    }, {
      classEffect: "bounceInDown",
      delay: "200ms",
      duration: "1s",
      href: "https://seryogagithub.github.io/projects/visa/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/8.jpg?raw=true',
      alt: "visa"
    }, {
      classEffect: "bounceInRight",
      delay: "1500ms",
      duration: "2s",
      href: "http://www.inform-vs.ru/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/9.jpg?raw=true',
      alt: "inform-vs"
    }, {
      classEffect: "rollIn",
      delay: "500ms",
      duration: "1.5s",
      href: "http://ortomed.com.ua/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/10.jpg?raw=true',
      alt: "ortomed"
    }, {
      classEffect: "bounceInDown",
      delay: "300ms",
      duration: "3s",
      href: "http://sklad-pro.com/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/11.jpg?raw=true',
      alt: "sklad-pro"
    }, {
      classEffect: "bounceInRight",
      delay: "500ms",
      duration: "1s",
      href: "https://meets.com/login",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/13.jpg?raw=true',
      alt: "meets.com"
    }, {
      classEffect: "bounceInDown",
      delay: "800ms",
      duration: "0.5s",
      href: "https://seryogagithub.github.io/projects/language/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/14.jpg?raw=true',
      alt: "arabic-school"
    }, {
      classEffect: "bounceInLeft",
      delay: "500ms",
      duration: "1s",
      href: "http://html.dimbrowsky.info/chernjak/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/17.jpg?raw=true',
      alt: "chernjak"
    }, {
      classEffect: "bounceInDown",
      delay: "800ms",
      duration: "0.5s",
      href: "http://html.dimbrowsky.info/auto/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/20.jpg?raw=true',
      alt: "auto"
    }, {
      classEffect: "bounceInLeft",
      delay: "500ms",
      duration: "1s",
      href: "http://html.dimbrowsky.info/circus/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/15.jpg?raw=true',
      alt: "circus"
    }, {
      classEffect: "bounceInRight",
      delay: "400ms",
      duration: "1s",
      href: "http://html.dimbrowsky.info/chetkin/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/16.jpg?raw=true',
      alt: "chetkin"
    }, {
      classEffect: "bounceInDown",
      delay: "200ms",
      duration: "1s",
      href: "http://dimbrowsky.com/km/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/18.jpg?raw=true',
      alt: "km"
    }, {
      classEffect: "bounceInRight",
      delay: "1500ms",
      duration: "2s",
      href: "https://carbonconsulting.com.ua/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/19.jpg?raw=true',
      alt: "carbonconsulting"
    }, {
      classEffect: "bounceInUp",
      delay: "300ms",
      duration: "1s",
      href: "http://rubineta.com/b2b/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/21.jpg?raw=true',
      alt: "rubineta"
    }, {
      classEffect: "rollIn",
      delay: "1500ms",
      duration: "2s",
      href: "http://html.dimbrowsky.info/art/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/22.jpg?raw=true',
      alt: "art"
    }, {
      classEffect: "bounceInDown",
      delay: "200ms",
      duration: "1s",
      href: "http://html.dimbrowsky.info/tehno/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/24.jpg?raw=true',
      alt: "tehno"
    }, {
      classEffect: "bounceInLeft",
      delay: "900ms",
      duration: "2s",
      href: "http://imperialgarage.net/auto/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/23.jpg?raw=true',
      alt: ""
    }, {
      classEffect: "bounceInUp",
      delay: "700ms",
      duration: "1.5s",
      href: "http://html.dimbrowsky.info/tech-razv/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/25.jpg?raw=true',
      alt: "tech-razv"
    }, {
      classEffect: "lightSpeedIn",
      delay: "1500ms",
      duration: "0.4s",
      href: "https://seryogagithub.github.io/projects/ubm/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/26.jpg?raw=true',
      alt: "ubm"
    }, {
      classEffect: "bounceInLeft",
      delay: "500ms",
      duration: "0.6s",
      href: "https://seryogagithub.github.io/projects/millioneris/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/27.jpg?raw=true',
      alt: "millioneris"
    }, {
      classEffect: "bounceInUp",
      delay: "700ms",
      duration: "0.4s",
      href: "https://seryogagithub.github.io/projects/simpleat/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/28.jpg?raw=true',
      alt: "simpleat"
    }, {
      classEffect: "bounceInUp",
      delay: "400ms",
      duration: "0.4s",
      href: "https://seryogagithub.github.io/projects/2ru2/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/29.jpg?raw=true',
      alt: "2ru2"
    }, {
      classEffect: "bounceInUp",
      delay: "100ms",
      duration: "0.7s",
      href: "http://html.dimbrowsky.info/mg-studia/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/30.jpg?raw=true',
      alt: "mg-studia"
    }, {
      classEffect: "bounceInDown",
      delay: "200ms",
      duration: "1s",
      href: "https://seryogagithub.github.io/projects/enginering/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/31.jpg?raw=true',
      alt: "enginering"
    }, {
      classEffect: "bounceInUp",
      delay: "700ms",
      duration: "0.5s",
      href: "https://seryogagithub.github.io/projects/aist/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/32.jpg?raw=true',
      alt: "aist"
    }, {
      classEffect: "bounceInLeft",
      delay: "500ms",
      duration: "0.4s",
      href: "http://new.zr-code.com/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/33.jpg?raw=true',
      alt: "zr"
    }, {
      classEffect: "rollIn",
      delay: "1500ms",
      duration: "1.2s",
      href: "http://new.zr-code.com/project-page.html",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/34.jpg?raw=true',
      alt: "zr-project"
    }, {
      classEffect: "rollIn",
      delay: "1500ms",
      duration: "2s",
      href: "https://seryogagithub.github.io/projects/zoom/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/35.jpg?raw=true',
      alt: "zoom"
    }, {
      classEffect: "rollIn",
      delay: "1500ms",
      duration: "2s",
      href: "https://seryogagithub.github.io/projects/callenge/dist/",
      src: 'https://github.com/SeryogaGitHub/react-resume/blob/master/src/img/portfolio/36.jpg?raw=true',
      alt: "challenge"
    }
  ]
};

export default state;
